openapi: 3.0.0
info:
  title: FightPandemics API
  version: '1.0'
  description: The API for fightpandemics.com
  license:
    name: MIT
servers:
  - url: 'http://localhost:8000/api/v1'
    description: Local API V1
  - description: ''
paths: {}
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        accessToken:
          type: string
        dateJoined:
          type: string
        location:
          type: object
      required:
        - id
    Organisation:
      title: Organisation
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        name:
          type: string
      required:
        - id
        - userId
        - name
    Post:
      title: Post
      type: object
      properties:
        id:
          type: string
        authorId:
          type: string
        title:
          type: string
        description:
          type: string
        type:
          type: array
          items:
            type: string
        shareWith:
          type: array
          items:
            type: string
        looking:
          type: array
          items:
            type: string
        needs:
          type: array
          items:
            type: string
        comments:
          $ref: '#/components/schemas/Comment'
        tags:
          type: string
        langage:
          type: string
        website:
          type: string
        iosUrl:
          type: string
        androidUrl:
          type: string
        media:
          type: string
        postEmail:
          type: string
      required:
        - id
        - authorId
        - title
        - description
    Comment:
      title: Comment
      type: object
      properties:
        authorId:
          type: string
        postId:
          type: string
        comment:
          type: string
      required:
        - authorId
        - postId
        - comment
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
